"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useState, type ReactNode } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import { faHouse, faFolderOpen, faChartSimple, faComment, faCalendarDays, faWandMagicSparkles, faLightbulb, faEye, faUser, faUsers, faBookmark, faCircleHalfStroke, faArrowUp, faStar, faClipboardCheck, faChevronRight, faHeart, faShieldHalved, faMagnifyingGlass, faRocket, faArrowTrendUp } from "@fortawesome/free-solid-svg-icons";
import UnbuiltPageModal from "./UnbuiltPageModal";
import type { UnbuiltPage } from "@/data/unbuilt-pages";
import { insightProjects, periods, chapterTitles, sources, formatCount, dateLabel, insightDates } from "@/data/writer-insights";
import shell from "./WriterStudioShell.module.css";
import styles from "./WriterInsights.module.css";

const navigation = [["หน้าหลัก", faHouse, "home"], ["โปรเจกต์ของฉัน", faFolderOpen, "projects"], ["ข้อมูลเชิงลึก", faChartSimple, "insights"], ["ความคิดเห็น", faComment, "comments"], ["ตารางเผยแพร่", faCalendarDays, "schedule"], ["เครื่องมือ AI", faWandMagicSparkles, "tools"]] as const;
const tasks = ["เขียนตอนถัดไปให้เสร็จ", "ตอบความคิดเห็นของผู้อ่าน", "เพิ่มแท็กที่เกี่ยวข้องมากขึ้น", "โปรโมตตอนล่าสุดในชุมชน", "วางแผนพล็อตตอนถัดไป"];
function Icon({ icon }: { icon: IconDefinition }) { return <FontAwesomeIcon icon={icon} aria-hidden="true" className={styles.icon} />; }
function Panel({ title, icon, children, action, className = "" }: { title: string; icon: IconDefinition; children: ReactNode; action?: ReactNode; className?: string }) {
  return <section className={`ds-card ${styles.panel} ${className}`}><div className={styles.panelHeading}><Icon icon={icon} /><h2 className="text-ds-h3">{title}</h2>{action}</div>{children}</section>;
}
function Tabs({ items, value, onChange, label }: { items: readonly string[]; value: string; onChange: (value: string) => void; label: string }) {
  return <div className={styles.tabs} role="group" aria-label={label}>{items.map(item => <button type="button" key={item} aria-pressed={value === item} className={value === item ? styles.selected : ""} onClick={() => onChange(item)}>{item}</button>)}</div>;
}
function Donut({ values, center, caption, name }: { values: readonly number[]; center: string; caption: string; name: string }) {
  let offset = 0;
  return <div className={styles.donut}><svg viewBox="0 0 120 120" role="img" aria-label={name}><circle cx="60" cy="60" r="48" className={styles.ringTrack} />{values.map((value, index) => { const start = offset; offset += value; return <circle key={index} cx="60" cy="60" r="48" fill="none" pathLength="100" strokeDasharray={`${value} ${100 - value}`} strokeDashoffset={-start} className={styles[`tone${index}`]} />; })}</svg><div><strong className="text-ds-h3">{center}</strong><span className="text-ds-caption text-arn-muted">{caption}</span></div></div>;
}

export default function WriterInsights() {
  const [projectId, setProjectId] = useState("moon");
  const [days, setDays] = useState(30);
  const [trendMetric, setTrendMetric] = useState("ยอดอ่านทั้งหมด");
  const [chapterMetric, setChapterMetric] = useState("ยอดอ่าน");
  const [demographic, setDemographic] = useState("ความสนใจ");
  const [chapterIndex, setChapterIndex] = useState(7);
  const [checked, setChecked] = useState([true, true, false, false, false]);
  const [activePoint, setActivePoint] = useState<number | null>(null);
  const [showAll, setShowAll] = useState(false);
  const [expandedInsight, setExpandedInsight] = useState(false);
  const [pending, setPending] = useState<UnbuiltPage | null>(null);
  useEffect(() => {
    if (!pending) return;
    const close = (event: KeyboardEvent) => { if (event.key === "Escape") setPending(null); };
    window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close);
  }, [pending]);
  const openFeature = (name: string, code: string) => setPending({ name, code: `WRITE-${code.toUpperCase()}`, url: `/write/${code}`, trigger: name, status: "ยังไม่ได้ทำ" });
  const project = insightProjects.find(item => item.id === projectId)!;
  const period = periods.find(item => item.days === days)!;
  const total = Math.round(project.total * period.factor);
  const { start, end } = insightDates(days);
  const metrics = [
    { label: "ยอดอ่านทั้งหมด", value: formatCount(total), growth: 12, icon: faEye },
    { label: "ผู้อ่านใหม่", value: formatCount(Math.round(project.readers * period.factor)), growth: 28, icon: faUser },
    { label: "ผู้ติดตามเพิ่ม", value: formatCount(Math.round(project.followers * period.factor)), growth: 18, icon: faUsers },
    { label: "คนเก็บเข้าชั้น", value: formatCount(Math.round(project.likes * period.factor)), growth: 16, icon: faBookmark },
    { label: "อัตราอ่านจบ", value: `${project.completion}%`, growth: 9, icon: faCircleHalfStroke },
    { label: "ความคิดเห็นใหม่", value: formatCount(Math.round(project.comments * period.factor)), growth: 43, icon: faComment },
  ];
  const trendTotal = trendMetric === "ยอดอ่านทั้งหมด" ? total : Math.round(project.readers * period.factor);
  const weights = Array.from({ length: days }, (_, i) => 5 + i / days * 9 + Math.sin(i * .8) * 2 + (i / days > .72 && i / days < .84 ? 6 : 0));
  const weightSum = weights.reduce((sum, value) => sum + value, 0);
  const daily = weights.map(value => Math.round(value / weightSum * trendTotal));
  daily[daily.length - 1] += trendTotal - daily.reduce((sum, value) => sum + value, 0);
  const ceiling = Math.ceil(Math.max(...daily, 1) / 1000) * 1000;
  const points = daily.map((value, i) => [48 + i / (days - 1) * 544, 176 - value / ceiling * 148]);
  const line = points.map(point => point.join(",")).join(" ");
  const selectedPoint = activePoint ?? daily.indexOf(Math.max(...daily));
  const pointDate = new Date(start); pointDate.setUTCDate(start.getUTCDate() + selectedPoint);
  const chapters = chapterTitles.map((title, i) => ({ title: project.id === "sky" ? ["จุดเริ่มต้นใหม่", "ท้องฟ้าที่เปลี่ยนไป", "ผู้มาเยือน", "ประตูแห่งวันพรุ่งนี้", "โลกคู่ขนาน", "แสงแห่งความหวัง", "คำตอบจากดวงดาว", "ใต้ฟ้าเดียวกัน"][i] : title, number: project.chapters - 7 + i, views: Math.round(total * [.043, .051, .048, .039, .047, .058, .067, .077][i]), completion: Math.min(96, project.completion + [-5, -3, 1, -2, 3, 4, 8, 14][i]), comments: Math.round(project.comments * period.factor * [.04, .05, .06, .04, .07, .09, .11, .147][i]) }));
  const ranked = [...chapters].sort((a, b) => b.views - a.views);
  const currentChapter = chapters[chapterIndex];
  const audiences = demographic === "ความสนใจ" ? [["โรแมนติก", 68], ["แฟนตาซี", 52], ["ดราม่า", 46], ["ย้อนยุค", 38], ["การเมือง / ชิงไหวชิงพริบ", 28]] as const : demographic === "ช่วงอายุ" ? [["18–24 ปี", 42], ["25–34 ปี", 32], ["35–44 ปี", 16], ["45 ปีขึ้นไป", 10]] as const : [["ไทย", 86], ["ลาว", 6], ["สิงคโปร์", 4], ["ประเทศอื่น ๆ", 4]] as const;

  return <main className={`${shell.stage} ${styles.stage}`}><div className={`${shell.layout} ${styles.layout}`}>
    <aside className={`ds-card ${shell.navigation}`}><h2 className="text-ds-h3">Writer Studio</h2><nav aria-label="เมนูนักเขียน">{navigation.map(([label, icon, id]) => ["home", "projects", "insights", "comments", "schedule"].includes(id) ? <Link key={id} href={id === "home" ? "/write" : `/write/${id}`} aria-current={id === "insights" ? "page" : undefined} className={`${shell.navItem} ${id === "insights" ? shell.activeNav : ""}`}><Icon icon={icon} />{label}</Link> : <button key={id} type="button" className={shell.navItem} onClick={() => openFeature(label, id)}><Icon icon={icon} />{label}</button>)}</nav><div className={shell.quote}>ข้อมูลที่ดี<br />ทำให้เรื่องราวของคุณ<br />ไปได้ไกลกว่าเดิม<span>— ARN SPACE —</span></div></aside>
    <div className={styles.center}>
      <header className={styles.heading}><h1 className="text-ds-h1"><Icon icon={faChartSimple} /> ข้อมูลเชิงลึก</h1><p className="text-ds-body">เข้าใจผลงานและผู้อ่านของคุณให้ลึกขึ้น เพื่อสร้างเรื่องราวที่ดียิ่งกว่าเดิม</p><span className={styles.demo}>ข้อมูลตัวอย่าง · ยังไม่เชื่อมต่อสถิติจริง</span></header>
      <div className={styles.toolbar}><div className={`ds-card ${styles.projectPicker}`}><Image src={project.cover} alt={`ปก ${project.title}`} width={44} height={60} sizes="44px" /><div><label className="sr-only" htmlFor="insight-project">เลือกผลงาน</label><select id="insight-project" value={projectId} onChange={event => { setProjectId(event.target.value); setChapterIndex(7); setActivePoint(null); }}><option value="moon">จันทร์เหนือวังหลวง</option><option value="sky">Sky of Tomorrow</option><option value="draft">ร่างใหม่ของฉัน</option></select><p className="text-ds-caption text-arn-muted">{project.chapters} ตอน · {project.total ? "เผยแพร่แล้ว" : "ยังไม่เผยแพร่"}</p></div></div><div className={styles.periodControl}><Tabs items={periods.map(item => item.label)} value={period.label} label="ช่วงเวลาของข้อมูล" onChange={label => { setDays(periods.find(item => item.label === label)!.days); setActivePoint(null); }} /><span className={styles.dateRange}><Icon icon={faCalendarDays} /> {dateLabel(start)} – {dateLabel(end)}</span></div></div>
      {!total ? <section className={`ds-card ${styles.empty}`} role="status"><Icon icon={faChartSimple} /><h2 className="text-ds-h2">เรื่องราวของคุณกำลังจะเริ่มต้น</h2><p className="text-ds-body text-arn-muted">เมื่อเผยแพร่ตอนแรก ข้อมูลยอดอ่านและผู้อ่านจะปรากฏที่นี่</p><Link className="ds-button-secondary px-ds-4" href="/write/projects">กลับไปจัดการโปรเจกต์</Link></section> : <>
        <div className={styles.metrics} aria-label="สถิติภาพรวม">{metrics.map(metric => <article className={`ds-card ${styles.metric}`} key={metric.label}><span className={styles.metricIcon}><Icon icon={metric.icon} /></span><div><p className="text-ds-caption text-arn-muted">{metric.label}</p><strong className="text-ds-h2">{metric.value}</strong><span className={styles.growth}><Icon icon={faArrowUp} /> {metric.growth}%</span><p className="text-ds-caption text-arn-subtle">{days === 180 ? "เทียบช่วงก่อนหน้า" : `จาก ${days} วันก่อนหน้า`}</p></div></article>)}</div>
        <div className={styles.chartGrid}>
          <Panel title="แนวโน้มยอดอ่าน" icon={faChartSimple} action={<select className="ds-input" aria-label="สถิติในกราฟแนวโน้ม" value={trendMetric} onChange={event => setTrendMetric(event.target.value)}><option>ยอดอ่านทั้งหมด</option><option>ผู้อ่านใหม่</option></select>}><div className={styles.chartCaption}><span className="text-ds-caption text-arn-muted">{trendMetric} · {period.label}</span><span className={styles.chartReadout} aria-live="polite">{dateLabel(pointDate)} <strong>{formatCount(daily[selectedPoint])}</strong></span></div><svg viewBox="0 0 612 206" className={styles.lineChart} role="img" aria-label={`กราฟ${trendMetric}รายวัน รวม ${formatCount(trendTotal)}`}><defs><linearGradient id="insight-area" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="var(--arn-color-accent)" stopOpacity=".28" /><stop offset="100%" stopColor="var(--arn-color-accent)" stopOpacity="0" /></linearGradient></defs>{[0, 1, 2, 3, 4].map(i => <g key={i}><line x1="48" x2="592" y1={176 - i * 37} y2={176 - i * 37} className={styles.gridLine} /><text x="36" y={180 - i * 37} textAnchor="end">{formatCount(ceiling * i / 4)}</text></g>)}<polygon points={`48,176 ${line} 592,176`} fill="url(#insight-area)" /><polyline points={line} className={styles.trendLine} /><circle cx={points[selectedPoint][0]} cy={points[selectedPoint][1]} r="4" className={styles.activeDot} />{[0, Math.floor((days - 1) / 2), days - 1].map(i => { const date = new Date(start); date.setUTCDate(start.getUTCDate() + i); return <text key={i} x={points[i][0]} y="200" textAnchor={i === 0 ? "start" : i === days - 1 ? "end" : "middle"}>{dateLabel(date).replace(/\s\d{4}$/, "")}</text>; })}{points.map(([x], i) => <rect key={i} x={x - 544 / days / 2} y="24" width={544 / days} height="156" fill="transparent" onMouseEnter={() => setActivePoint(i)}><title>{`${dateLabel(new Date(start.getTime() + i * 86400000))}: ${daily[i].toLocaleString("en")} ${trendMetric}`}</title></rect>)}</svg><input type="range" className={styles.chartSlider} min={0} max={days - 1} value={selectedPoint} onChange={event => setActivePoint(Number(event.target.value))} aria-label="เลือกวันที่เพื่อดูสถิติยอดอ่าน" /></Panel>
          <Panel title="ยอดอ่านรายตอน" icon={faChartSimple} action={<Tabs items={["ยอดอ่าน", "อ่านจบ"]} value={chapterMetric} onChange={setChapterMetric} label="สถิติรายตอน" />}><div className={styles.barChart} role="group" aria-label="เลือกตอนเพื่อดูสถิติ">{chapters.map((chapter, i) => { const value = chapterMetric === "ยอดอ่าน" ? chapter.views / Math.max(...chapters.map(item => item.views)) * 100 : chapter.completion; return <button key={chapter.number} type="button" aria-pressed={chapterIndex === i} className={`${styles.barColumn} ${chapterIndex === i ? styles.activeBar : ""}`} onClick={() => setChapterIndex(i)}><span className={styles.barValue}>{chapterMetric === "ยอดอ่าน" ? formatCount(chapter.views) : `${chapter.completion}%`}</span><span className={styles.barTrack}><span className={styles.bar} style={{ height: `${value}%` }} /></span><span>ตอน {chapter.number}</span></button>; })}</div><p className="text-ds-caption text-arn-muted">{currentChapter.title} · อ่านจบ {currentChapter.completion}%</p></Panel>
        </div>
        <div className={styles.detailGrid}>
          <Panel title="Retention ผู้อ่าน" icon={faShieldHalved}><div className={styles.retention}>{[["เริ่มอ่านตอนแรก", 100], ["อ่านต่อ (ตอนที่ 2+)", 78], ["อ่านถึงครึ่งเรื่อง", 56], ["อ่านตอนล่าสุด", project.completion]].map(([label, value], i) => <div key={label}><span className={`${styles.funnel} ${styles[`funnel${i}`]}`} /><div><span className="text-ds-caption text-arn-muted">{label}</span><strong>{value}%</strong><span className="text-ds-caption text-arn-subtle">{formatCount(Math.round(total * Number(value) / 100))} ครั้งที่อ่าน</span></div></div>)}</div><p className="text-ds-caption text-arn-subtle">สัดส่วนการอ่านต่อจากตอนแรก</p></Panel>
          <Panel title="แหล่งที่มาของผู้อ่าน" icon={faChartSimple}><div className={styles.donutLayout}><Donut values={sources.map(item => item.value)} center={formatCount(total)} caption="ยอดอ่านทั้งหมด" name="แหล่งที่มาของยอดอ่าน: หน้าแรก 38%, ค้นหา 24%, แท็ก 18%, ชั้นหนังสือ 12%, ลิงก์แชร์ 6%, อื่น ๆ 2%" /><ul className={styles.legend}>{sources.map((source, i) => <li key={source.label}><span className={`${styles.legendDot} ${styles[`tone${i}`]}`} /><span>{source.label}</span><strong>{source.value}%</strong></li>)}</ul></div></Panel>
          <Panel title="ข้อมูลผู้อ่าน" icon={faUsers}><Tabs items={["ความสนใจ", "ช่วงอายุ", "ประเทศ"]} value={demographic} onChange={setDemographic} label="ประเภทข้อมูลผู้อ่าน" /><div className={styles.audiences}>{audiences.map(([label, value]) => <div key={label}><div><span>{label}</span><strong>{value}%</strong></div><progress value={value} max={100} aria-label={`${label} ${value}%`} /></div>)}</div>{demographic === "ความสนใจ" && <p className="text-ds-caption text-arn-subtle">ผู้อ่านหนึ่งคนอาจสนใจหลายหมวด</p>}</Panel>
        </div>
        <div className={styles.bottomGrid}>
          <Panel title="ความคิดเห็นของผู้อ่าน" icon={faComment}><div className={styles.sentiment}><div className={styles.donutLayout}><Donut values={[72, 18, 10]} center={metrics[5].value} caption="ความคิดเห็นใหม่" name="ความคิดเห็นเชิงบวก 72%, เป็นกลาง 18%, ข้อเสนอแนะ 10%" /><ul className={styles.legend}>{[["เชิงบวก", 72], ["เป็นกลาง", 18], ["ข้อเสนอแนะ", 10]].map(([label, value], i) => <li key={label}><span className={`${styles.legendDot} ${styles[`tone${i}`]}`} /><span>{label}</span><strong>{value}%</strong></li>)}</ul></div><div className={styles.quotes}><blockquote>“เนื้อเรื่องเข้มข้นมาก รอตอนต่อไปเลย!”</blockquote><blockquote>“ตัวละครมีมิติมาก ชอบบทสนทนาค่ะ”</blockquote><blockquote>“อยากให้ขยายฉากของตัวละครรองอีกนิด”</blockquote></div></div></Panel>
          <Panel title="ตอนที่ได้รับความนิยมสูงสุด" icon={faCalendarDays} action={<button type="button" className={styles.textAction} onClick={() => setShowAll(value => !value)}>{showAll ? "แสดงน้อยลง" : "ดูทั้งหมด"} <Icon icon={faChevronRight} /></button>}><div className={styles.tableScroll}><table><caption className="sr-only">ตอนยอดนิยม เรียงตามยอดอ่าน</caption><thead><tr><th scope="col">ชื่อตอน</th><th scope="col">ยอดอ่าน</th><th scope="col">อ่านจบ</th><th scope="col">ความคิดเห็น</th></tr></thead><tbody>{ranked.slice(0, showAll ? 8 : 5).map(chapter => <tr key={chapter.number}><th scope="row"><button type="button" onClick={() => setChapterIndex(chapters.indexOf(chapter))}>ตอน {chapter.number} — {chapter.title}</button></th><td>{formatCount(chapter.views)}</td><td>{chapter.completion}%</td><td>{chapter.comments}</td></tr>)}</tbody></table></div></Panel>
        </div>
        <div className={styles.keywordGrid}><Panel title="คำค้น / แท็กที่ผู้อ่านสนใจ" icon={faMagnifyingGlass}><ol className={styles.keywords}>{[project.title, "นิยายย้อนยุค", "วังหลวง", "โรแมนติก", "ดราม่า", "คำสัญญา", "ความลับ", "การเมือง", "แฟนตาซี", "ชะตารัก"].map((word, i) => <li key={word}><span>{i + 1}</span>{word}<small>{formatCount(Math.round(total * (.029 - i * .002)))}</small></li>)}</ol></Panel><Panel title="คำแนะนำการเผยแพร่" icon={faCalendarDays} className={styles.publish}><p className="text-ds-body-sm text-arn-muted">ช่วงเวลาที่ผู้อ่านของคุณมีส่วนร่วมมากที่สุด</p><strong>วันศุกร์ · 19:00 – 21:00</strong><p className="text-ds-caption text-arn-subtle">จากข้อมูลตัวอย่างในช่วง {period.label}</p><button type="button" className="ds-button-secondary" onClick={() => openFeature("ตารางเผยแพร่", "schedule")}>วางแผนการเผยแพร่ <Icon icon={faChevronRight} /></button></Panel></div>
      </>}
    </div>
    {total > 0 && <aside className={styles.rail} aria-label="สรุปและคำแนะนำ">
      <Panel title="สรุปเร็ว" icon={faClipboardCheck}><p className="sidebar-meta text-arn-muted">{period.label === "ทั้งหมด" ? "ตั้งแต่เริ่มเผยแพร่" : `${period.label}ที่ผ่านมา`}</p><div className={styles.summary}>{metrics.map(metric => <div key={metric.label}><Icon icon={metric.icon} /><span className="sidebar-meta text-arn-muted">{metric.label}</span><strong>{metric.value}</strong><span className={styles.growth}><Icon icon={faArrowUp} /> {metric.growth}%</span></div>)}</div></Panel>
      <Panel title="AI Insight" icon={faStar} className={styles.aiPanel}><p className="sidebar-meta text-arn-muted">แนวทางจากการวิเคราะห์ข้อมูลตัวอย่าง</p><div className={styles.insightItem}><Icon icon={faArrowTrendUp} /><p className="sidebar-body">ตอนที่ {project.chapters - 1}–{project.chapters} มีอัตราอ่านจบสูงกว่าค่าเฉลี่ย ลองต่อยอดจังหวะการเล่าเรื่องในตอนถัดไป</p></div><div className={styles.insightItem}><Icon icon={faHeart} /><p className="sidebar-body">ความคิดเห็นเชิงบวกคิดเป็น 72% ผู้อ่านชื่นชอบตัวละครและบทสนทนา</p></div><div className={styles.insightItem}><Icon icon={faLightbulb} /><p className="sidebar-body">ช่วงเย็น 19:00–21:00 เป็นเวลาที่เหมาะกับการเผยแพร่ตอนใหม่</p></div>{expandedInsight && <p className={`sidebar-body ${styles.insightDetail}`}>ลองจบตอนด้วยคำถามหรือปมใหม่ และชวนผู้อ่านแสดงความคิดเห็นเพื่อเพิ่มการมีส่วนร่วม คำแนะนำนี้เป็นตัวอย่างและยังไม่ได้ประมวลผลด้วย AI จริง</p>}<button type="button" className="ds-button-secondary" aria-expanded={expandedInsight} onClick={() => setExpandedInsight(value => !value)}>{expandedInsight ? "ย่อคำแนะนำ" : "ดูคำแนะนำเพิ่มเติม"} <Icon icon={faChevronRight} /></button></Panel>
      <Panel title="สิ่งที่ควรทำต่อ" icon={faClipboardCheck}><p className="sidebar-meta text-arn-muted">เหลือ {checked.filter(value => !value).length} รายการ</p><div className={styles.tasks}>{tasks.map((label, i) => <label key={label}><input type="checkbox" checked={checked[i]} onChange={() => setChecked(values => values.map((value, index) => index === i ? !value : value))} /><span className="sidebar-body">{label}</span></label>)}</div></Panel>
      <Panel title="เปรียบเทียบตอนล่าสุด" icon={faRocket}><select className={`ds-input ${styles.chapterSelect}`} aria-label="เลือกตอนเพื่อดูรายละเอียด" value={chapterIndex} onChange={event => setChapterIndex(Number(event.target.value))}>{chapters.map((chapter, i) => <option value={i} key={chapter.number}>ตอนที่ {chapter.number}</option>)}</select><div className={styles.chapterBook}><Image src={project.cover} alt={`ปก ${project.title}`} width={60} height={88} sizes="60px" /><div><h3 className="sidebar-item-title">ตอนที่ {currentChapter.number}</h3><p className="sidebar-body">{currentChapter.title}</p><span className="sidebar-meta text-arn-muted">เทียบกับตอนก่อนหน้า</span></div></div>{[["ยอดอ่าน", formatCount(currentChapter.views), chapterIndex > 0 ? `${Math.round((currentChapter.views / chapters[chapterIndex - 1].views - 1) * 100)}%` : "—"], ["อัตราอ่านจบ", `${currentChapter.completion}%`, chapterIndex > 0 ? `${currentChapter.completion - chapters[chapterIndex - 1].completion} จุด` : "—"], ["ความคิดเห็น", String(currentChapter.comments), chapterIndex > 0 ? `${currentChapter.comments - chapters[chapterIndex - 1].comments}` : "—"]].map(([label, value, change]) => <div className={styles.compareRow} key={label}><span>{label}</span><strong>{value}</strong><span>{change.startsWith("-") || change === "—" ? change : `+${change}`}</span></div>)}<button className="ds-button-secondary" type="button" onClick={() => openFeature(`รายละเอียดตอนที่ ${currentChapter.number}`, `manage/${project.id}`)}>ดูรายละเอียดตอน <Icon icon={faChevronRight} /></button></Panel>
    </aside>}
  </div>{pending && <UnbuiltPageModal page={pending} href={pending.url} onClose={() => setPending(null)} />}</main>;
}
